### ISSUE TITLE
how to install this could you explain I don't understand for me it's not working

### ISSUE THREAD

**Issue by ghost** [Rhystic1/EURadio#1]
how to install this could you explain I don't understand for me it's not working

**Comment by Rhystic1** [comment]
Hello, 
You can't really "install" this: it's a Skill for Alexa which hasn't been made public yet due to some critical bugs that still needs fixing. However, if you want access, I can send you a link to become a beta tester for it, which would allow you to access it on most Alexa devices.

**Comment by saniellocutor** [comment]
O'QUE could send the link to test

**Comment by saniellocutor** [comment]
Ok could you send me the link to test
